/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 *
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern u8 curHTTPID;

void HTTPPrint(u32 callbackID);
void HTTPPrint_btn1(void);
void HTTPPrint_pot(void);
void HTTPPrint_temp(void);
void HTTPPrint_myMAC(u16);
void HTTPPrint_myIP(u16);
void HTTPPrint_myGate(u16);
void HTTPPrint_myMask(u16);
void HTTPPrint_my1DNS(u16);
void HTTPPrint_my2DNS(u16);
void HTTPPrint_myDHCP(void);

void HTTPPrint(u32 callbackID)
{
    switch(callbackID)
    {
        case 0x00000000:
            HTTPPrint_btn1();
            break;
        case 0x00000001:
            HTTPPrint_pot();
            break;
        case 0x00000002:
            HTTPPrint_temp();
            break;
        case 0x00000007:
            HTTPPrint_myMAC(0);
            break;
        case 0x00000008:
            HTTPPrint_myMAC(1);
            break;
        case 0x00000009:
            HTTPPrint_myMAC(2);
            break;
        case 0x0000000a:
            HTTPPrint_myMAC(3);
            break;
        case 0x0000000b:
            HTTPPrint_myMAC(4);
            break;
        case 0x0000000c:
            HTTPPrint_myMAC(5);
            break;
        case 0x0000000d:
            HTTPPrint_myIP(0);
            break;
        case 0x0000000e:
            HTTPPrint_myIP(1);
            break;
        case 0x0000000f:
            HTTPPrint_myIP(2);
            break;
        case 0x00000010:
            HTTPPrint_myIP(3);
            break;
        case 0x00000011:
            HTTPPrint_myGate(0);
            break;
        case 0x00000012:
            HTTPPrint_myGate(1);
            break;
        case 0x00000013:
            HTTPPrint_myGate(2);
            break;
        case 0x00000014:
            HTTPPrint_myGate(3);
            break;
        case 0x00000015:
            HTTPPrint_myMask(0);
            break;
        case 0x00000016:
            HTTPPrint_myMask(1);
            break;
        case 0x00000017:
            HTTPPrint_myMask(2);
            break;
        case 0x00000018:
            HTTPPrint_myMask(3);
            break;
        case 0x00000019:
            HTTPPrint_my1DNS(0);
            break;
        case 0x0000001a:
            HTTPPrint_my1DNS(1);
            break;
        case 0x0000001b:
            HTTPPrint_my1DNS(2);
            break;
        case 0x0000001c:
            HTTPPrint_my1DNS(3);
            break;
        case 0x0000001d:
            HTTPPrint_my2DNS(0);
            break;
        case 0x0000001e:
            HTTPPrint_my2DNS(1);
            break;
        case 0x0000001f:
            HTTPPrint_my2DNS(2);
            break;
        case 0x00000020:
            HTTPPrint_my2DNS(3);
            break;
        case 0x00000021:
            HTTPPrint_myDHCP();
            break;
        default:
            // Output notification for undefined values
            TCPPutROMArray(sktHTTP, (const u8*)"!DEF", 4);
    }

    return;
}

void HTTPPrint_(void)
{
    TCPPut(sktHTTP, '~');
    return;
}

#endif

#endif
